# Survey Bot Configuration

# Discord Bot Configuration
discord:
  token: ${DISCORD_TOKEN}
  guild_id: ${DISCORD_GUILD_ID}
  prefix: "!"
  intents:
    - message_content
    - guilds
    - guild_messages
    - guild_reactions
    - guild_members

# Channel Configuration
channels:
  # Survey Bot channels (optional - will be created if needed)
  survey_notifications: "survey-notifications"
  earnings_updates: "earnings-updates"
  error_logs: "error-logs"
  system_status: "system-status"
  withdrawal_confirmations: "withdrawal-confirmations"

# CPX Research Configuration
cpx_research:
  base_url: "https://offers.cpx-research.com/index.php"
  app_id: "27806"
  ext_user_id: "533055960609193994_1246050346233757798"
  secure_hash: "49069f12991d2283f61a52dc967dff9f"
  username: ${CPX_USERNAME}
  password: ${CPX_PASSWORD}
  
  # Survey Completion Settings
  survey_settings:
    min_earnings: 0.10  # Minimum earnings to accept survey
    max_time: 30        # Maximum time in minutes
    auto_accept: true   # Automatically accept surveys
    random_delays: true # Add random delays to appear human
    
  # Survey Types to Target
  survey_types:
    - "gaming"
    - "technology"
    - "entertainment"
    - "sports"
    - "shopping"
    - "general"

# Web Scraping Configuration
web_scraper:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  timeout: 30
  retry_attempts: 3
  headless: true
  window_size:
    width: 1920
    height: 1080

# Database Configuration
database:
  url: "sqlite:///data/survey_bot.db"
  backup_interval: 24  # hours

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/survey_bot.log"
  max_size: "10MB"
  backup_count: 5



# Discord Commands Integration
discord_commands:
    
  # Survey Commands
  survey_commands:
    - "survey"
    - "earnings"
    - "status"
    - "withdraw"
    
  # Gaming Commands (from the Discord server)
  gaming_commands:
    - "setup"
    - "profile"
    - "mine"
    - "fish"
    - "rob"
    - "open"
    - "refine"
    - "learn"
    - "craft"
    - "blow-up"
    - "enchant"
    - "shop"
    - "sell"
    - "offers"
    - "withdraw"
    - "pet"
    - "feed"
    - "switch"
    - "battle"
    - "tip"
    - "rain"
    - "magic-storm"
    - "invites"
    - "leaderboards"
    - "codex"
    - "emoji"
    - "flex"
    - "pings"

# Security Settings
security:
  rate_limiting: true
  max_requests_per_minute: 60
  ip_rotation: false
  proxy_enabled: false

# Notification Settings
notifications:
  discord_webhook: ${DISCORD_WEBHOOK_URL}
  email_notifications: false
  earnings_threshold: 1.00  # Notify when earnings reach this amount
